name: Run tests

on:  
  schedule:
    - cron: '*/5 * * * *'  # every day at midnight
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Get Covid-19 Notification on WhatsApp!
        run: |
          curl --request GET \
          --url 'https://google-apis-serverless.vercel.app/api/covid-19'